package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"testing"

	"gitbay.org/gitbay/internal/control"
)

var updateSummaries = flag.Bool("update", false, "rewrite summaries_gen.go")

// summaries_gen.go is the registry's one-line summaries, so the CLI's
// command list and completions say what help says.
func TestSummariesAreCurrent(t *testing.T) {
	var b strings.Builder
	b.WriteString("// Code generated by TestSummariesAreCurrent -update; DO NOT EDIT.\n\npackage main\n\nvar summaries = map[string]string{\n")
	var lines []string
	for _, cmd := range control.Commands() {
		lines = append(lines, fmt.Sprintf("\t%q: %q,\n", strings.Join(cmd.Path, " "), cmd.Summary))
	}
	slices.Sort(lines)
	b.WriteString(strings.Join(lines, ""))
	b.WriteString("}\n")
	want, err := format.Source([]byte(b.String()))
	if err != nil {
		t.Fatal(err)
	}
	if *updateSummaries {
		os.WriteFile("summaries_gen.go", want, 0o644)
	}
	got, _ := os.ReadFile("summaries_gen.go")
	if string(got) != string(want) {
		t.Fatal("summaries_gen.go is stale: go test ./cmd/gitbay -run TestSummariesAreCurrent -update")
	}
}

func TestRootSectionsCoverEveryCommand(t *testing.T) {
	seen := map[string]int{}
	for _, s := range rootSections {
		for _, n := range s.names {
			seen[n]++
		}
	}
	for _, c := range newRoot().Commands() {
		name := c.Name()
		if name == "help" || name == "completion" {
			continue
		}
		if seen[name] != 1 {
			t.Errorf("%s is in %d root sections", name, seen[name])
		}
	}
}

func TestGroupsSayWhatTheServerSays(t *testing.T) {
	nouns := control.NounSummaries()
	for _, c := range newRoot().Commands() {
		if s, ok := nouns[c.Name()]; ok && c.Short != s {
			t.Errorf("%s: CLI says %q, server says %q", c.Name(), c.Short, s)
		}
	}
}
