ALTER TABLE users ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN website TEXT NOT NULL DEFAULT '';
ALTER TABLE orgs ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE orgs ADD COLUMN website TEXT NOT NULL DEFAULT '';
