ALTER TABLE users ADD COLUMN about TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN about_format TEXT NOT NULL DEFAULT 'md';
ALTER TABLE users ADD COLUMN links TEXT NOT NULL DEFAULT '';
ALTER TABLE orgs ADD COLUMN about TEXT NOT NULL DEFAULT '';
ALTER TABLE orgs ADD COLUMN about_format TEXT NOT NULL DEFAULT 'md';
ALTER TABLE orgs ADD COLUMN links TEXT NOT NULL DEFAULT '';
